# Configuration file for H-Proj baseline

defaults:
  - model: hproj
  - dataset: cvx_qcqp
  - _self_

# Experiment settings
seed: 123
wandb_workspace: ConstrainedNN
wandb_project:
wandb_name:

# Hydra output management
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
